DROP TABLE IF EXISTS Events;

CREATE TABLE IF NOT EXISTS Events (
  id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  job_id UNIQUEIDENTIFIER NOT NULL,
  type TEXT NOT NULL,
  data TEXT NOT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_job_events ON Events (job_id, event_type, timestamp);