DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
  id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
  username TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  org TEXT NOT NULL
);

CREATE INDEX idx_username ON Users (username);

INSERT INTO Users (id, username, org) VALUES ('00000000-0000-0000-0000-000000000000', 'admin', '<ROOT>');
